server:
  port: 8000
  
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICE
        uri:
          lb://CITIZEN-SERVICE
        predicates:
        - Path=/CoWIN/**
        
      - id: VACCINATION-CENTER
        uri:
          lb://VACCINATION-CENTER
        predicates:
        - Path=/coWin/vaccine/**
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
      